name: ai.luca
favicon: null
layout_spectrum: 0.75394
typography_spectrum: 0.34849
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffb100'
    - '#fbfeff'
    - '#040000'
    - '#c76c00'
    - '#553e00'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
